---
pagetitle: "Schedule"

---
::: grid

::: {#sponsors_banner .g-col-12 .title}
# Course Program
This course is equivalent to 3 Academic Credits (135 Hours)
:::

::: {.g-col-12 .full_text_block}
> **Note:** The schedule below is tentative and subject to change based on field conditions, instructor availability, and logistical considerations.

```{mermaid}
gantt
    title ISC Biotrop 2026 – Course Schedule by Sessions
    dateFormat  YYYY-MM-DD
    axisFormat  %d %b

    section Orientation
    Arrival in Yogyakarta                             :2026-06-28, 1d
    Welcoming & Course Orientation                    :2026-06-29, 1d
    Indonesian Language and Culture Learning (INCULS) :2026-06-29, 4d

    section Pre-Assignments
    Intro Video Submission             :milestone, 2026-07-05, 1d
    Essay on Biodiversity Challenges   :milestone, 2026-07-05, 1d

    section Pre-Course (In Class Hybrid | 6–9 July)
    Lecture and Classes   :2026-07-06, 4d
    
    section Social (Optional) 
    Welcoming Dinner (Optional)      :a8, 2026-07-12, 1d

    section Onsite Course (13–18 July)
    Opening & Field Prep       :2026-07-13, 1d
    (2D1N) Field Sampling      :2026-07-14, 2d
    Laboratory Sessions :2026-07-16, 2d

    section Student Conference
    Summit & ISC Closing           :2026-07-18, 1d

    section Satellite Event
    Ramban Rimba with Genau Foundation :2026-07-21, 3d
    Program Wrap up and Closing :2026-07-24, 2d
```

### Course Orientation (Online) | 29 June 2026

The orientation will explain the pre-course assignments and reading materials, how to access learning platforms, using GitHub and GitHub Codespaces for computer assignments, schedules, and communication tools.

### Pre-Course assignments

Prior to the start of the course, participants are assigned several tasks:

- Reading materials and basic coding skill preparation
- 1-2 minutes introduction video about you and why you are interested to join this course
- An essay on the current challenges faced by Tropical Biodiversity and opportunities in the age of data and AI

### Pre-Course (Online Hybrid) | 6 - 9 July 2026

| Day | Date | Session | Topic | Activities |
|---|---|----|-------|-----------|
| Day 1 | Mon, 6/7/26 | Online | Tropical Biodiversity in the Data Age | Lectures on biodiversity challenges, data types, and course overview |
| Day 2 | Tue, 7/7/26 | Online | Study Design, Sampling, & Metadata | Sampling design, metadata standards, ethics and mini exercise |
| Day 3 | Wed, 8/7/26 | Online | Genomics for Biodiversity Assesment | Bioinformatics practicals on metabarcoding, metagenomics, and biodiversity analysis |
| Day 4 | Thu, 9/7/26 | Online | From Data to Impact | Bioprospecting, GIS data analysis, policy case studies |
: {.striped .hover}

### Onsite Course | 13 - 19 July 2026

| Day | Date | Session | Topic | Activities |
|---|---|----|-------|-----------|
| Optional Event | Sun, 12/7/26 | Welcoming Dinner | Greetings and getting to know each other | |
| Day 5 | Mon, 13/7/26 | Lab | Welcoming Ceremony & Field Sampling Preparation | Opening session, course briefing, introduction to field and safety protocols |
| Day 6 | Tue, 14/7/26 | Field | Field Sampling Day 1 (Terrestrial Ecosystems) | Terrestrial sampling (soil, plants, insects), environmental measurements, GIS data acquisition using drones |
| Day 7 | Wed, 15/7/26 | Field | Field Sampling Day 2 (Coastal/Intertidal) | Intertidal sampling, water sampling, ecological observations, metadata recording |
| Day 8 | Thu, 16/7/26 | Lab | From Sample to DNA | DNA extraction, quality control (QC), Library Preparation for Next-Generation Sequencing |
| Day 9 | Fri, 17/7/26 | Computer | From Genomes to Landscapes | Sequence data processing, integrating biodiversity data with GIS and spatial mapping |
| Day 10 | Sat, 18/7/26 | Biodiversity Summit | From Data to Decisions | Group presentations, translating results into policy recommendations, discussion & closing |
: {.striped .hover}

### Post Course assignments

Participant will be assigned to create a project report or analysis portofolio on what they learn during the course using GitHub pages.

:::

:::