gantt
    title ISC Biotrop 2026 – Course Schedule by Sessions
    dateFormat  YYYY-MM-DD
    axisFormat  %d %b

    section Orientation
    NCP Welcoming & Course Orientation :2026-06-29, 1d

    section Satellite Event I
    Ramban Rimba with Genau Foundation :2026-06-30, 3d

    section Pre-Assignments
    Intro Video Submission             :milestone, 2026-07-05, 1d
    Essay on Biodiversity Challenges   :milestone, 2026-07-05, 1d

    section Pre-Course (Online Hybrid | 6–9 July)
    Biodiversity in Data Age   :2026-07-06, 1d
    Study Design & Metadata    :2026-07-07, 1d
    Genomics & Bioinformatics  :2026-07-08, 1d
    GIS, Data, and Policy      :2026-07-09, 1d
    
    section Social (Optional) 
    Welcoming Dinner (Optional)      :a8, 2026-07-12, 1d

    section Onsite Course (13–18 July)
    Opening & Field Prep       :2026-07-13, 1d
    (2D1N) Field Sampling      :2026-07-14, 2d
    DNA Extraction & Sequencing :2026-07-16, 1d
    Data Analysis & GIS        :2026-07-17, 1d

    section Student Conference
    Summit & Closing           :2026-07-18, 1d

    section Satellite Event II & Closing
    Sustainable Agriculture Practices with PIAT UGM  :2026-07-21, 2d
    Cultural Trip and NCP Closing :2026-07-23, 2d