project:
  type: website
  output-dir: _site
  preview:
    port: 4200
    browser: false

website:
  title: "ISC Biotrop 2026"
  #subtitle: "From Ecosystems to Repositories: Data-Driven Insights into Tropical Biodiversity"
  sidebar: false
  navbar:
    background: light
    pinned: false
    right:
      - href: index.qmd
        text: Home
      - text: About
        menu:
          - text: ISC Biotrop 2026
            href: about/about.qmd
          - text: Organizing committee
            href: about/organizers.qmd
          - text: Sponsors
            href: about/sponsors/
      - text: Program
        href: program/schedule/
      - text: Speakers
        href: program/speakers/
      - text: Register
        href: register.qmd
      #- text: Participation
      #  menu: 
          #- text: Code of conduct
          #  href: participation/coc.qmd
          #- text: Key dates
          #  href: participation/keydates/
      - text: Contact
        href: contact.qmd
  page-footer: 
    left: |

      ::: {.column width="100%"}
      ![](/img/faculty_biology_ugm.png){fig-align="left" style="max-width: 50%; margin-right: 10px; max-height: 50px;"}
      :::
      Supported by Universitas Gadjah Mada Equity Grant 2026
    right: 
      - icon: globe
        href: https://iscbiotrop.org/
      - icon: envelope
        href: mailto:oia.biology@ugm.ac.id

format:
  html:
    theme: 
      light: [cosmo, css/styles.scss]
      #dark: darkly
    page-layout: custom
    toc: false

editor: visual

