---
title: ""
format:
  html:
    include-after-body:
      - js/countdown.js
      
listing:
  - id: countdown
    template: countdown.ejs
    contents: 
      - datetime: July 6, 2026 23:59:00
  - id: sponsors
    template: about/sponsors/sponsors.ejs
    contents: about/sponsors/sponsors.yml
---

::: grid
::: {#banner_small .g-col-12}
#### International Summer Course on Tropical Biodiversity and Sustainable Development
# From Ecosystems to Repositories
## Data-Driven Insights into Tropical Biodiversity

#### 6-9 July 2026 (Hybrid Pre-Course) | 13-18 July 2026 (Onsite Course){style="max-width: fit-content; max-width: -moz-fit-content;"}

#### @ Universitas Gadjah Mada, Yogyakarta, Indonesia
:::

::: {#countdown .g-col-12}
:::

::: {.g-col-6 .text_block}
### About ISC Biotrop 2026

The International Summer Course (ISC) Biotrop 2026 is an annual program organized by the Faculty of Biology, Universitas Gadjah Mada, welcoming students from around the world to explore Tropical Biology and sustainable development practices in Indonesia and the ASEAN region.

This year’s theme, "**From Ecosystems to Repositories: Data-Driven Insights into Tropical Biodiversity**", highlights the growing role of data in understanding and protecting biodiversity. This 10-day program combines **four days of online lectures** with **six days of intensive onsite activities**, providing participants with an end-to-end learning experience—from field sampling in tropical ecosystems to data analysis and interpretation.

Participants will gain hands-on experience in biodiversity through the lense of **DNA sequencing** and **Geographical Information System (GIS)**, while also learning how to translate scientific data into meaningful insights for conservation and policy. The course is designed for students and early-career researchers interested in tropical ecosystems, genomics, and data-driven approaches to biodiversity assessment, bioprospecting, and conservation.
:::

::: {.g-col-6 .img_margin}
<iframe
  width="100%" height="400"
  src="https://www.youtube.com/embed/tXC557UOYBY?si=EBvna14W5JVExh6H?autoplay=1&mute=1"
  title="YouTube video player"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
  referrerpolicy="strict-origin-when-cross-origin"
  allowfullscreen>
</iframe>
:::

::: {#sponsors .g-col-12}
:::
:::
